---
apiVersion: image.openshift.io/v1
kind: List
metadata:
  name: fluentd
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: {{ .values.imageStream.name }}
  spec:
    lookupPolicy:
      local: false
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: fluentd
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: {{ .values.imageStream.base.kind }}
        name: {{ .values.imageStream.base.from }}
      generation: 1
      importPolicy: {}
      name: {{ .values.imageStream.base.name }}
      referencePolicy:
        type: Source
...