apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  replicas: 1
  selector:
    app: fluentd
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Vienna
          image: fluentd
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - >-
                  tail -1 /fluentd/log/fluent.log | grep -q
                  Mongo::Auth::Unauthorized; test $? != 0
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: fluentd
          ports:
            - containerPort: 24224
              protocol: TCP
            - containerPort: 5140
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /fluentd/log
              name: fluentd-log-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: fluentd-log-volume
          persistentVolumeClaim:
            claimName: fluentd-log-claim
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - fluentd
        from:
          kind: ImageStreamTag
          name: 'fluentd:latest'
          namespace: 57-hogarama
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/57-hogarama/fluentd@sha256:e04e5e2b836e6081c352bd736daf1839caa362bc3f4ab166ab2244f85bf51e83
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-11-13T06:01:14Z'
      lastUpdateTime: '2019-11-13T06:01:15Z'
      message: replication controller "fluentd-241" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2019-11-15T14:17:50Z'
      lastUpdateTime: '2019-11-15T14:17:50Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
  details:
    causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: >-
              docker-registry.default.svc:5000/57-hogarama/fluentd@sha256:e04e5e2b836e6081c352bd736daf1839caa362bc3f4ab166ab2244f85bf51e83
        type: ImageChange
    message: image change
  latestVersion: 241
  observedGeneration: 427
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
