apiVersion: v1
kind: ImageStream
metadata:
  generation: 1
  name: fluentd
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: fluent/fluentd:edge-debian
    generation: 1
    importPolicy: {}
    name: edge-debian
    referencePolicy:
      type: Source
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/fluentd
