version: "~> 1.0"
os: linux
language: shell
notifications:
  email:
    on_success: change
    on_failure: never
  slack:
    rooms:
      secure: RtFo61bif5/nWdA35CjIGQutziEY7hD8+PvSlpIGMJzJO889sws9CAoCVRVYV3Y1y+Kog5YG4yQ9q+ZRSxI5CFY+CZAdZOqBeB6T3DFZ9YKE5E3iEsGb99DE+eNkhiwDhlfFEtv99ibrLtdRkVekXuntlxy7uM+3YBk6X7qcmfpmi+HS0/fdtcwi5QqPfdv5gVu1TvaAtXnaLbagMw2AEpNCb4W/YbziqfF9FW+pe0MF1t5KdoouRYZ8/HIN+ggjD3oT4s9idKB4qD/qypTHgIlSSGfSQeSFiRlRnftqmpo7l/3fOOTNw7CF8XLihKP/qmE//eclVQUGethntWH0pOnuD+YgVGS1BhayElyJC5qZc8WVNgCXM4/qEuZQhntWZiUKcIvBq1ieDdN9+pse9RmrX1HP+aR37W5AnD8iVexzpejy1uMAFWriY0Wetdo8oz0udocjyYyCFcRv/ovSszafZWeGuu3t6bqE9Mxf21k1PIKv+bzbvLgPiLlU5PA/QCZ9vC60RcTC5WS0L7AjtjPQvr5njQVtgy0tJpA8kHUL6GK8CJAsGG5at5nljBPZsMFBLdYINc/lOfH6k6cXancFK9JtzoT8ZyWYdIwlZNDeJrn0Jp2dul91JzlhXGRByAfeKtIlkLZ7HG70I0dSi+p7QC8qGyjERbFGt4y4Djs=
    template:
      - "%{commit_subject}"
      - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
      - by %{author} %{result} in %{duration}
    on_success: never
    on_failure: always
script:
  - mv secrets/dummy-secrets.yml secrets/secrets.yml
  - helm/hogarama/helm_prerequisites.sh -f -b dummy-branch
  - helm/tests/template.sh