#!/bin/bash

function amq () {
  local git_branch=${1}
  local namespace=${2}
  local oc_admin_token=${3}
  local oc_cluster=${4}

  execute """
   oc delete --kubeconfig=/home/.admin cm amq-configs -n ${namespace};
   oc create --kubeconfig=/home/.admin cm amq-configs -n ${namespace} \
    --from-file=${TOPLEVEL_DIR}/configs/amq/broker.xml \
    --from-file=${TOPLEVEL_DIR}/configs/amq/entrypoint.sh
  """

  execute """
  oc delete --kubeconfig=/home/.admin secret amq-secret -n ${namespace};
  oc create --kubeconfig=home/.admin secret generic amq-secret -n ${namespace} \
    --from-file=${TOPLEVEL_DIR}/secrets/amq/broker.ks
  """
  
  execute """
  oc delete --kubeconfig=/home/.admin secret amq-credentials -n ${namespace};
  oc create --kubeconfig=home/.admin secret generic amq-credentials -n ${namespace} \
    --from-literal=AMQ_USER="amq" \
    --from-literal=AMQ_PASSWORD="amq@123"
  """
  
  oc-create-from-template "admin" ${namespace} "resources/amq/imagestream.yml"
  oc-create-resource "admin" ${namespace} "resources/amq/amq-deploymentconfig.yml"
  oc-create-resource "admin" ${namespace} "resources/amq/service.yml"
  oc-create-resource "admin" ${namespace} "resources/amq/mqtt-route.yml"
  oc-create-resource "admin" ${namespace} "resources/amq/console-route.yml"
}
readonly -f amq
[ "$?" -eq "0" ] || return $?
