#!/bin/bash

#######################
# READ ONLY VARIABLES #
#######################

readonly PROGNAME=`basename "$0"`
readonly SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
readonly TOPLEVEL_DIR=$( cd ${SCRIPT_DIR}/../.. > /dev/null && pwd )

##########
# SOURCE #
##########

for functionFile in ${TOPLEVEL_DIR}/bootstrap/functions/*.active;do source ${functionFile}; done

############
# oc_setup #
############

oc_setup() {
   # initial values
  local git_branch=${1}
  local namespace=${2}
  local oc_admin_token=${3}
  local oc_cluster=${4}

  oc_create_resource "admin" ${namespace} "resources/grafana/grafana-configmap.yml"
  oc_create_resource "admin" ${namespace} "resources/grafana/imagestream.yml"
  #oc_create_resource "admin" ${namespace} "resources/grafana/pvc.yml"
  oc_create_resource "admin" ${namespace} "resources/grafana/grafana-deploymentconfig.yml"
  oc_create_resource "admin" ${namespace} "resources/grafana/service.yml"
  oc_create_resource "admin" ${namespace} "resources/grafana/route.yml"
#  oc_create_resource "admin" ${namespace} "resources/grafana/grafana-subscription.yml"
#  oc_create_resource "admin" ${namespace} "resources/grafana/crd.yml"
}
readonly -f oc_setup
[ "$?" -eq "0" ] || return $?

hogarama_main $@