#!/bin/bash

#######################
# READ ONLY VARIABLES #
#######################

readonly PROGNAME=`basename "$0"`
readonly SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
readonly TOPLEVEL_DIR=$( cd ${SCRIPT_DIR}/../.. > /dev/null && pwd )

##########
# SOURCE #
##########

for functionFile in ${TOPLEVEL_DIR}/bootstrap/functions/*.active;do source ${functionFile}; done

############
# oc_setup #
############

oc_setup() {
   # initial values
  local git_branch=${1}
  local namespace=${2}
  local oc_admin_token=${3}
  local oc_cluster=${4}

  oc_create_resource "admin" ${namespace} "resources/hogajama/s2i-builder-maven-is.yml"
  oc_create_resource "admin" ${namespace} "resources/hogajama/maven-is.yml"
  oc_create_resource "admin" ${namespace} "resources/hogajama/hogajama-binary-is.yml"
  oc_create_resource "admin" ${namespace} "resources/hogajama/hogajama-binary-bc.yml"
  oc_create_resource "admin" ${namespace} "resources/hogajama/s2i-builder-maven-bc.yml"
  oc_create_resource "admin" ${namespace} "resources/hogajama/hogajama-binary-bc.yml" # "--param GIT_BRANCH=master" #TODO: change to template && change to ${git_branch} after merging back into hogarama repository
  oc_create_resource "admin" ${namespace} "resources/hogajama/hogajama-run-is.yml"
  oc_create_resource "admin" ${namespace} "resources/hogajama/hogajama-run-bc.yml"

  execute """
  oc delete --kubeconfig=/home/.admin cm hogajama-standalone -n ${namespace}
  oc create --kubeconfig=/home/.admin cm hogajama-standalone -n ${namespace} \
    --from-file=${TOPLEVEL_DIR}/configs/hogajama/standalone-openshift.xml
  """
  
  oc_create_resource "admin" ${namespace} "resources/hogajama/eap-subscription.yml"
  oc_create_resource "admin" ${namespace} "resources/hogajama/crd.yml"

}

hogarama_main $@