---
timezone: "Europe/Vienna"
credentials:
  mongo_username: max
  mongo_password: muster
imageStream:
  name: "fluentd-hogarama"
  base:
    name: fluentd
    tag: "edge-debian"
    kind: "DockerImage"
    from: "fluent/fluentd:edge-debian"
trigger:
  github: 
    secret: "abc"
  generic:
    secret: "def"
...