apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    application: sso
    template: sso71-postgresql-persistent
    xpaas: 1.4.0
  name: sso
spec:
  selector:
    deploymentConfig: sso
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        application: sso
        deploymentConfig: sso
      name: sso
    spec:
      containers:
#        - env:
#            - name: OPENSHIFT_KUBE_PING_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  apiVersion: v1
#                  fieldPath: metadata.namespace
        - image: registry.access.redhat.com/redhat-sso-7/sso71-openshift
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /opt/eap/bin/jboss-cli.sh
                  - -c
                  - :shutdown(timeout=60)
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/eap/bin/livenessProbe.sh
          name: sso
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8888
              name: ping
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/eap/bin/readinessProbe.sh
          resources: {}
          volumeMounts:
            - mountPath: /etc/eap-secret-volume
              name: eap-keystore-volume
              readOnly: true
            - mountPath: /etc/jgroups-encrypt-secret-volume
              name: eap-jgroups-keystore-volume
              readOnly: true
            - mountPath: /etc/sso-secret-volume
              name: sso-truststore-volume
              readOnly: true
      volumes:
        - name: eap-keystore-volume
          secret:
            defaultMode: 420
            secretName: sso-app-secret
        - name: eap-jgroups-keystore-volume
          secret:
            defaultMode: 420
            secretName: sso-app-secret
        - name: sso-truststore-volume
          secret:
            defaultMode: 420
            secretName: sso-app-secret
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - sso
        from:
          kind: ImageStreamTag
          name: redhat-sso71-openshift:1.1
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
