apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: gepardec
  labels:
    app: sso
spec:
  realm:
    id: gepardec
    realm: gepardec
    enabled: true
    displayName: gepardec
    identityProviders: [
      {
        "providerId": "google",
        "displayName": "Google",
        "enabled": true,
        "webOrigins": "*",
        "redirectUris" : "*",
        "alias": "google",
        "BrowserRedirectorIdentityProvider": "google",
        "config": {
          "alias": "google",
          "clientId": "987100582349-jeg9d0jkbmi3aoiumfnmsrsa9jcs86f4.apps.googleusercontent.com",
          "clientSecret": "4jPV5SoIkhxxlZR0s_NFaM8L"
        }
      }
      ]
  instanceSelector:
    matchLabels:
      app: sso
