apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: gepardec
  labels:
    app: sso
spec:
  realm:
    id: hogarama
    realm: hogarama
    enabled: true
    displayName: hogarama
    identityProviders: [
      {
        "providerId": "google",
        "displayName": "Google",
        "enabled": true,
        "webOrigins": "*",
        "redirectUris" : "*",
        "alias": "google",
        "BrowserRedirectorIdentityProvider": "google",
        "config": {
          "alias": "google",
# TODO Template and add new clientid and secet
        }
      }
      ]
  instanceSelector:
    matchLabels:
      app: sso
