apiVersion: v1
kind: ImageStream
metadata:
  generation: 1
  name: prometheus
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: prom/prometheus:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
