apiVersion: v1
kind: Template
metadata:
  name: hogarama-amq-bc
parameters:
  - name: GIT_REPO
    description: "please provide the git repo url"
    value: https://github.com/Gepardec/HogaramaInfrastructure
  - name: GIT_BRANCH
    description: "please provide the git branch"
    value: master
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: amq
    name: amq
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'amq:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git: 
        uri: "${GIT_REPO}"
        ref: "${GIT_BRANCH}"
      contextDir: "/lib/amq/broker" 
      dockerfile: |
        FROM amq-broker-72-openshift:latest
        COPY --chown=jboss:0 . /home/jboss/lib/
    strategy: 
      type: Docker
      dockerStrategy:
        from:
          kind: "ImageStreamTag"
          name: "amq-broker-72-openshift:latest"
    output: 
      to:
        kind: "ImageStreamTag"
        name: "amq:latest"
    triggers:
      - github:
          secret: 4m9EY9lErQRrs8LJjudP
        type: GitHub
      - generic:
          secret: A2YAGDWxu2zgCfjIyo25
        type: Generic
      - imageChange:
        type: ImageChange
      - type: ConfigChange
