apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: amq
  name: amq
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'amq:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git: 
      uri: "https://github.com/Gepardec/HogaramaInfrastructure"
      ref: "feature/amq"
    contextDir: "/lib/amq/broker" 
    dockerfile: |
      FROM amq:lastest
      COPY . /home/jboss/broker/lib
  strategy: 
    type: Docker
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: "amq:latest"
  output: 
    to:
      kind: "ImageStreamTag"
      name: "myamq:latest"
  triggers:
    - github:
        secret: 4m9EY9lErQRrs8LJjudP
      type: GitHub
    - generic:
        secret: A2YAGDWxu2zgCfjIyo25
      type: Generic
    - imageChange:
      type: ImageChange
    - type: ConfigChange
