apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: amq
  labels:
    app: amq
    name: amq
spec:
  replicas: 1
  selector:
    app: amq
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: amq
    spec:
      containers:
      - command:
        - /home/jboss/cfg/entrypoint.sh
        env:
        - name: TZ
          value: Europe/Vienna
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: https://secure-sso-57-hogarama.cloud.itandtel.at/auth/
        envFrom:
        - secretRef:
            name: amq-credentials
        image: registry.access.redhat.com/amq-broker-7/amq-broker-72-openshift:latest
        imagePullPolicy: Always
        name: amq
        ports:
        - containerPort: 61616
          protocol: TCP
        - containerPort: 5672
          protocol: TCP
        - containerPort: 61613
          protocol: TCP
        - containerPort: 5445
          protocol: TCP
        - containerPort: 1883
          protocol: TCP
        - containerPort: 8883
          protocol: TCP
        - containerPort: 8161
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/jboss/cfg
          name: amq-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: amq-volume
        projected:
          defaultMode: 360
          sources:
          - secret:
              name: amq-secrets
          - configMap:
              name: amq-configs
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - amq
      from:
        kind: ImageStreamTag
        name: amq:latest
    type: ImageChange