apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-03-22T07:27:58Z'
  labels:
    app: amq72
  name: amq72-mqtt-ssl
  namespace: hogarama
  selfLink: /oapi/v1/namespaces/hogarama/routes/amq72-mqtt-ssl
  uid: 0431bb5c-4c74-11e9-94a6-00155d648649
spec:
  host: amq72-mqtt-ssl-hogarama.10.0.75.2.nip.io
  port:
    targetPort: 8883-tcp
  tls:
    termination: passthrough
  to:
    kind: Service
    name: amq72
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-03-22T07:27:58Z'
          status: 'True'
          type: Admitted
      host: amq72-mqtt-ssl-hogarama.10.0.75.2.nip.io
      routerName: router
      wildcardPolicy: None
