apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2019-03-15T07:19:51Z'
  labels:
    app: amq72
  name: amq72
  namespace: hogarama
  selfLink: /apis/build.openshift.io/v1/namespaces/hogarama/buildconfigs/amq72
  uid: b90c6d4d-46f2-11e9-bb10-00155d648647
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'amq72:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: AMQ/AMQ72
    git:
      ref: amq72
      uri: 'https://github.com/Gepardec/Hogarama'
    type: Git
  strategy:
    type: Docker
  triggers:
    - github:
        secret: 4m9EY9lErQRrs8LJjudP
      type: GitHub
    - generic:
        secret: A2YAGDWxu2zgCfjIyo25
      type: Generic
    - imageChange:
      type: ImageChange
    - type: ConfigChange
