apiVersion: v1
kind: Template
metadata:
  labels:
    app: hogajama-binary
  name: hogajama-binary
parameters:
  - name: GIT_REPO
    description: "please provide the git repo url"
    value: https://github.com/Gepardec/Hogarama
  - name: GIT_BRANCH
    description: "please provide the git branch"
    value: master
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: hogajama-binary
      name: hogajama-binary
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'hogajama-binary:latest'
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 's2i-builder-maven:latest'
          type: Source
          env:
            - name: BUILDER_CONTEXT_DIR
              value: Hogajama
            - name: BUILDER_MVN_OPTIONS
              value: '-P ocp-aws'
      postCommit: {}
      source:
        type: Git
        git:
          uri: 'https://github.com/Gepardec/Hogarama'
          ref: "${GIT_BRANCH}"
      triggers:
        - type: GitHub
          github:
            secret: Wq63PpZLl2SRdPKX5l-9
        - type: Generic
          generic:
            secret: HY6-6pQ-JxdDsvKVUb9p
        - type: ConfigChange
        - type: ImageChange
      runPolicy: Serial
