apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  serviceAccount: anyuid-builder
  output:
    to:
      kind: ImageStreamTag
      name: 'fluentd-hogarama:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: "Dockerfile"
    dockerfile: |-
{{ .Files.Get "files/fluentd/Dockerfile" | indent 6 }}
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: '{{ .Values.imageStream.base.name }}:{{ .Values.imageStream.base.tag }}'
    type: Docker
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
