{
 "title": "Hogarama",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Arduino Demo Panel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hogarama_sensor_value{sensor_location=\"ToteGazelle\"} OR hogarama_sensor_value{sensor_location=\"Simba\"} OR hogarama_sensor_value{sensor_location=\"imPark\"}"
    }
   ]
  },
  {
   "title": "Sensor values",
   "type": "graph",
   "description": "Sensor values of all plants",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hogarama_sensor_value" }
   ]
  },
  {
   "title": "Sensor Value Vienna",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hogarama_sensor_value{sensor_location=\"Wien\"} OR hogarama_sensor_value{sensor_location=\"ToteGazelle\"} OR hogarama_sensor_value{sensor_location=\"Jamal\"} OR hogarama_sensor_value{sensor_location=\"Nala\"} OR hogarama_sensor_value{sensor_location=\"Simba\"} "
    }
   ]
  },
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 } },
  {
   "title": "Pump Activation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hogarama_watering_events_fired{Sensor_Name=\"GruenerGepard\"}[2m])"
    }
   ]
  },
  {
   "title": "Requests latency seconds count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(hogarama_requests_latency_seconds_count[5m])"
    },
    {
     "expr": "deriv(hogarama_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Varianz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(hogarama_sensor_value{sensor_name=\"GruenerGepard\"}[1m])"
    }
   ]
  }
 ]
}