apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-hogarama
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: false
    auth.anonymous:
      enabled: false
    log:
      level: warn
      mode: console
    security:
      admin_password: admin@123!
      admin_user: admin
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana-dashboard
            - grafana
  compat:
    fixAnnotations: true   # Allows importing dashboards that specify annotation tags as arrays instead of strings.
    fixHeights: true
