apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - access: proxy
      editable: false
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: prometheus
      type: prometheus
      url: 'prometheus-57-hogarama.cloud.itandtel.at'
      version: 1
  name: grafana-datasources.yaml
