apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-online
spec:
  channel: stable
  name: amq-online 
  source: redhat-operators
  sourceNamespace: openshift-marketplace