apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: test-operators
spec:
  channel: beta
  name: prometheus 
  source: community-operators
  sourceNamespace: openshift-marketplace